version: "3.8"
services:
  postgres:
    image: postgres:11.10-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PG_DATABASE_USER}
      - POSTGRES_PASSWORD=${PG_DATABASE_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE_NAME}
    ports:
      - "5432:5432"
