// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/errors.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorDetail struct {
	ErrorCode            string            `protobuf:"bytes,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ErrorDetail) Reset()         { *m = ErrorDetail{} }
func (m *ErrorDetail) String() string { return proto.CompactTextString(m) }
func (*ErrorDetail) ProtoMessage()    {}
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_176b67d994589ed1, []int{0}
}

func (m *ErrorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDetail.Unmarshal(m, b)
}
func (m *ErrorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDetail.Marshal(b, m, deterministic)
}
func (m *ErrorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDetail.Merge(m, src)
}
func (m *ErrorDetail) XXX_Size() int {
	return xxx_messageInfo_ErrorDetail.Size(m)
}
func (m *ErrorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDetail proto.InternalMessageInfo

func (m *ErrorDetail) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *ErrorDetail) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorDetail) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorDetail)(nil), "pb.ErrorDetail")
	proto.RegisterMapType((map[string]string)(nil), "pb.ErrorDetail.MetaEntry")
}

func init() {
	proto.RegisterFile("proto/errors.proto", fileDescriptor_176b67d994589ed1)
}

var fileDescriptor_176b67d994589ed1 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2d, 0x2a, 0xca, 0x2f, 0x2a, 0xd6, 0x03, 0x73, 0x84, 0x98, 0x0a, 0x92, 0x94,
	0xd6, 0x32, 0x72, 0x71, 0xbb, 0x82, 0x04, 0x5d, 0x52, 0x4b, 0x12, 0x33, 0x73, 0x84, 0x64, 0xb8,
	0x38, 0xc1, 0x6a, 0x9c, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02,
	0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0x4c, 0x60, 0x39, 0x18,
	0x57, 0x48, 0x97, 0x8b, 0x25, 0x37, 0xb5, 0x24, 0x51, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb, 0x48,
	0x52, 0xaf, 0x20, 0x49, 0x0f, 0xc9, 0x58, 0x3d, 0xdf, 0xd4, 0x92, 0x44, 0xd7, 0xbc, 0x92, 0xa2,
	0xca, 0x20, 0xb0, 0x32, 0x29, 0x73, 0x2e, 0x4e, 0xb8, 0x90, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a,
	0x25, 0xd4, 0x36, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x14, 0x66, 0x0b, 0x84,
	0x63, 0xc5, 0x64, 0xc1, 0xe8, 0xc4, 0x16, 0xc5, 0xa2, 0xa7, 0x5f, 0x90, 0x94, 0xc4, 0x06, 0xf6,
	0x82, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xa0, 0x27, 0x75, 0xd8, 0x00, 0x00, 0x00,
}
