// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName             string               `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Users)(nil), "pb.Users")
}

func init() {
	proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5)
}

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x95, 0x34, 0x89, 0x9a, 0xd3, 0x05, 0x59, 0x0c, 0x51, 0x90, 0x20, 0xea, 0x42, 0x26,
	0x47, 0x2a, 0x13, 0x63, 0x79, 0x00, 0x86, 0x08, 0x16, 0x96, 0xca, 0x26, 0xa7, 0x55, 0x25, 0x1b,
	0x5b, 0xbe, 0xbc, 0x02, 0xcf, 0x8d, 0x7c, 0x09, 0x6b, 0x37, 0x9f, 0xf3, 0xfd, 0x9f, 0xf5, 0xdb,
	0x70, 0xa7, 0x8d, 0x72, 0x6a, 0xf2, 0x16, 0x0d, 0x8d, 0x47, 0x52, 0x6a, 0xde, 0x3f, 0x5d, 0x94,
	0xba, 0x08, 0x9c, 0xe2, 0x86, 0xfb, 0xf3, 0xe4, 0xae, 0x12, 0xad, 0x63, 0x52, 0xa7, 0xd0, 0xfe,
	0xb7, 0x84, 0xea, 0xd3, 0xa2, 0x21, 0x3d, 0x6c, 0x83, 0xfb, 0xc3, 0x24, 0x76, 0xc5, 0x50, 0x8c,
	0xed, 0xfc, 0x3f, 0x93, 0x07, 0x68, 0xcf, 0x5e, 0x88, 0x53, 0x84, 0x65, 0x82, 0x61, 0xf1, 0x1e,
	0xe0, 0x3d, 0xd4, 0x28, 0xd9, 0x55, 0x74, 0x9b, 0x08, 0xd2, 0x40, 0x5e, 0x01, 0xbe, 0x0d, 0x32,
	0x87, 0xcb, 0x89, 0xb9, 0xae, 0x1a, 0x8a, 0x71, 0x77, 0xe8, 0x69, 0x6a, 0x43, 0xd7, 0x36, 0xf4,
	0x63, 0x6d, 0x33, 0xb7, 0x39, 0x7d, 0x74, 0x41, 0xf5, 0x7a, 0x59, 0xd5, 0xfa, 0xb6, 0x9a, 0xd3,
	0x49, 0x5d, 0x50, 0x60, 0x56, 0x9b, 0xdb, 0x6a, 0x4e, 0x1f, 0xdd, 0xfe, 0x19, 0xea, 0xf0, 0x0f,
	0x96, 0x3c, 0x42, 0x1d, 0x1e, 0x6e, 0xbb, 0x62, 0xd8, 0x8c, 0xbb, 0xc3, 0x96, 0x6a, 0x4e, 0x03,
	0x99, 0xd3, 0xfa, 0xad, 0xf9, 0xaa, 0xe8, 0xa4, 0x39, 0x6f, 0xe2, 0x7d, 0x2f, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x76, 0xe2, 0xfc, 0xed, 0x79, 0x01, 0x00, 0x00,
}
